apiVersion: v1
appVersion: 1.3.0
description: A Helm chart for Kubernetes Tagger
home: https://github.com/oxyno-zeta/kubernetes-tagger
maintainers:
  - email: havrileckalexandre@gmail.com
    name: oxyno-zeta
name: kubernetes-tagger
sources:
  - https://github.com/oxyno-zeta/kubernetes-tagger
version: 1.1.1
