apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prometheus-cachethq.fullname" . }}-config
  labels:
{{ include "prometheus-cachethq.labels" . | indent 4 }}
data:
  config.yaml: {{ .Values.config | quote }}
