apiVersion: v1
kind: Service
metadata:
  name: {{ include "prometheus-cachethq.fullname" . }}
  labels:
{{ include "prometheus-cachethq.labels" . | indent 4 }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
{{- if hasKey .Values.service "nodePort" }}
      nodePort: {{ .Values.service.nodePort }}
{{- end }}
    - port: 9090
      targetPort: internal
      protocol: TCP
      name: metrics
  {{- if .Values.service.clusterIP }}
  clusterIP: "{{ .Values.service.clusterIP }}"
  {{- end }}
  {{- if .Values.service.externalIPs }}
  externalIPs:
  {{ toYaml .Values.service.externalIPs | nindent 4 }}
  {{- end }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: "{{ .Values.service.loadBalancerIP }}"
  {{- end }}
  {{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{ toYaml .Values.service.loadBalancerSourceRanges | indent 4 }}
  {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "prometheus-cachethq.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
