{{- if .Values.secretFiles }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "s3-proxy.fullname" . }}-secret-files
  labels:
    app.kubernetes.io/name: {{ include "s3-proxy.name" . }}
    helm.sh/chart: {{ include "s3-proxy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
{{- range $key, $value := .Values.secretFiles }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
{{- end }}
